# Generated by Django 4.2.5 on 2023-10-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_alter_directory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                related_query_name="file",
                to="files.directory",
            ),
        ),
    ]
