# Generated by Django 4.2.5 on 2023-11-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_alter_file_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="directory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                related_query_name="file",
                to="files.directory",
            ),
            preserve_default=False,
        ),
    ]
