name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        wget https://dl.min.io/server/minio/release/linux-amd64/minio
        chmod +x minio
        mv minio /usr/local/bin/
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        mv mc /usr/local/bin/mc
    - name: Start minio server
      run: |
        mkdir -p ~/minio
        minio server ~/minio --console-address :9090 &
    - name: Set minio alias
      run: |
        mc alias set test http://127.0.0.1:9000 minioadmin minioadmin
    - name: Set access and secret keys
      run: |
        mc admin user svcacct add                      \
          --access-key "${{ secrets.S3_ACCESS_KEY }}"  \
          --secret-key "${{ secrets.S3_SECRET_KEY }}"  \
          test minioadmin
    - name: Run Tests
      run: |
        cd src
        python manage.py test --parallel
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_SECURE_CONNECTION: ${{ secrets.S3_SECURE_CONNECTION }}
