name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        wget https://dl.min.io/server/minio/release/linux-amd64/minio
        chmod +x minio
        mv minio /usr/local/bin/
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        mv mc /usr/local/bin/mc
    - name: Start minio server
      run: |
        mc admin user svcacct add                      \
          --access-key "${{ secrets.S3_ACCESS_KEY }}"  \
          --secret-key "${{ secrets.S3_SECRET_KEY }}"  \
          test minioadmin
        mkdir -p ~/minio
        minio server ~/minio --console-address :9090
    - name: Run Tests
      run: |
        python src/manage.py test --parallel
